language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - '280304286@163.com'
    on_success: always # default: change
    on_failure: always # default: always
node_js:
  - '8'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
